name: Test Jupyter Bot (Run Every Minute for 3 Minutes)

on:
  workflow_dispatch:  
  schedule:
    - cron: '0 */2 * * *'  # Runs every other hour

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Jupyter Notebook for Testing
        env:
          ITERATIONS: 1  # Limit the bot to run for 3 iterations
        run: |
          for i in $(seq 1 $ITERATIONS); do
            echo "Running iteration $i..."
            jupyter nbconvert --to notebook --execute bot_poster.ipynb --output bot_poster_$i.ipynb
            sleep 60  # Wait for 1 minute between runs
          done
