name: Test Jupyter Bot (Run Every Minute for 3 Minutes)

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually for testing
  schedule:
    - cron: '* * * * *'  # Runs every minute

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Jupyter Notebook for Testing
        env:
          ITERATIONS: 3  # Limit the bot to run for 3 iterations
        run: |
          for i in $(seq 1 $ITERATIONS); do
            echo "Running iteration $i..."
            jupyter nbconvert --to notebook --execute your_notebook.ipynb --output executed_notebook_$i.ipynb
            sleep 60  # Wait for 1 minute between runs
          done
